# Generated by Django 5.1.1 on 2025-01-27 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0002_carmodel_location_thirdpartymaintenance_car_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_ID', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reservation_plan', models.CharField(choices=[('2H', '2 Hours'), ('6H', '6 Hours'), ('12H', '12 Hours')], max_length=3)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=10)),
                ('duration', models.FloatField()),
                ('review_rate', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Review rate from 1 to 5')),
                ('review_text', models.TextField(help_text='Review text about the park')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_V3.car')),
                ('reservation_Locatiion_Distnation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_reservations', to='ride_V3.location')),
                ('reservation_Locatiion_Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_reservations', to='ride_V3.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
