# Generated by Django 5.1.1 on 2025-01-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0005_alter_reservationhistory_review_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='location',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='car',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='car',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_Locatiion_Source',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='reservation_Locatiion_Distnation',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='reservation_Locatiion_Source',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Fine',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='ThirdPartyMaintenance',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationHistory',
        ),
    ]
