# Generated by Django 5.1.1 on 2024-11-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0014_alter_payment_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='xrideuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='xrideuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='XrideUser',
        ),
    ]
