# Generated by Django 5.1.1 on 2024-11-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0015_remove_reservation_car_remove_reservation_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
