# Generated by Django 5.1.1 on 2024-11-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='e.g., Tesla Model 3, Ford Focus', max_length=255, unique=True)),
                ('manufacturer', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('engine_type', models.CharField(choices=[('electric', 'Electric'), ('diesel', 'Diesel')], default='diesel', max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('additional_features', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maintenance_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(max_length=20, unique=True)),
                ('door_status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='locked', max_length=10)),
                ('temperature', models.FloatField()),
                ('location_latitude', models.FloatField()),
                ('location_longitude', models.FloatField()),
                ('reservation_status', models.CharField(choices=[('reserved', 'Reserved'), ('available', 'Available')], default='available', max_length=10)),
                ('booking_price_2H', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_price_6H', models.DecimalField(decimal_places=2, max_digits=8)),
                ('booking_price_12H', models.DecimalField(decimal_places=2, max_digits=8)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_V3.carmodel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_V3.location')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('tire_replacement', 'Tire Replacement'), ('brake_inspection', 'Brake Inspection'), ('battery_replacement', 'Battery Replacement'), ('engine_tuning', 'Engine Tuning'), ('fluid_check', 'Fluid Check'), ('filter_change', 'Filter Change'), ('suspension_inspection', 'Suspension Inspection'), ('alignment', 'Alignment'), ('ac_service', 'A/C Service'), ('lights_check', 'Lights Check'), ('general_inspection', 'General Inspection'), ('other', 'Other')], help_text='Type of maintenance, e.g., oil change, tire rotation', max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_V3.car')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_V3.thirdpartymaintenance')),
            ],
        ),
    ]
