# Generated by Django 5.1.1 on 2024-11-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0023_remove_reservationhistory_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationHistory',
        ),
    ]
