# Generated by Django 5.1.1 on 2024-11-11 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0028_alter_payment_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
