# Generated by Django 5.1.1 on 2025-01-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0030_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XrideUser',
        ),
    ]
