# Generated by Django 5.1.1 on 2025-01-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0032_user_alter_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='kary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
            ],
        ),
    ]
