# Generated by Django 5.1.1 on 2025-01-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V3', '0033_kary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='car',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='user',
        ),
        migrations.DeleteModel(
            name='kary',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservationhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Fine',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='ReservationHistory',
        ),
    ]
