# Generated by Django 5.1.1 on 2024-10-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='car',
            name='door_status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='close', max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved')], default='available', max_length=10),
        ),
    ]
