# Generated by Django 5.1.1 on 2024-10-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V1', '0002_remove_car_reserved_by_car_door_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
