# Application Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xride-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xride
  template:
    metadata:
      labels:
        app: xride
    spec:
      containers:
      - name: xride-container
        image: macarious25siv/project:Xride_V0
        ports:
        - containerPort: 8000    # Update with the port your application listens on

---
# Application Service
apiVersion: v1
kind: Service
metadata:
  name: xride-service
  namespace: dev
spec:
  selector:
    app: xride
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort