# Generated by Django 5.1.1 on 2024-10-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0.0)),
                ('door_status', models.CharField(default='locked', max_length=10)),
            ],
        ),
    ]
