# Generated by Django 5.1.1 on 2024-10-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ride_V2', '0002_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0.0)),
                ('door_status', models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked')], default='close', max_length=8)),
            ],
        ),
    ]
