# Generated by Django 5.1.1 on 2024-10-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V2', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gas',
            field=models.FloatField(default=0.0),
        ),
    ]
