# Use the official MySQL image from Docker Hub
FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=123456789
ENV MYSQL_DATABASE=my_django_db
ENV MYSQL_USER=kary
ENV MYSQL_PASSWORD=123456789

# Copy any custom configuration files if needed
# COPY ./my-custom.cnf /etc/mysql/conf.d/

# Expose the default MySQL port
EXPOSE 3306
