# FROM python:3.11-alpine 
# WORKDIR /app 
# COPY requirements.txt . 
# RUN pip install --upgrade pip 
# RUN pip install -r requirements.txt 
# COPY . . 
# EXPOSE 8000 
# CMD [ "python","manage.py","runserver","0.0.0.0:8000" ] 


FROM python:3.11-alpine 

ENV PYTHONDONTWRITEBYTECODE=1 
ENV PYTHONUNBUFFERED=1 
# Install dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    libmysqlclient-dev \
    pkg-config

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Upgrade pip and install Python packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 8000

# Command to run your application (adjust as needed)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
