# FROM python:3.11-alpine 
# WORKDIR /app 
# COPY requirements.txt . 
# RUN pip install --upgrade pip 
# RUN pip install -r requirements.txt 
# COPY . . 
# EXPOSE 8000 
# CMD [ "python","manage.py","runserver","0.0.0.0:8000" ] 

FROM python:3.11-alpine

# Install dependencies
RUN apk update && apk add --no-cache \
    gcc \
    musl-dev \
    mariadb-dev \
    pkgconfig

# Set working directory
WORKDIR /app

# Copy requirements file
COPY requirements.txt .

# Upgrade pip and install Python packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 8000

# Command to run your application (adjust as needed)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
