# Generated by Django 5.1.1 on 2024-10-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_V0', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
